### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by pcrombach** [aparshin/leaflet-boundary-canvas#16]
I have some options in my Tilelayer from another plugin: L.TileLayer.PouchDBCached.js

These options are : useCache and cacheMaxAge

It seems those additional options are not passed into the L.TileLayer.PouchDBCached layer.

There are no tiles from a Boundary-canvas layer stored in the pouchDb cache.
How do I fix this???

**Comment by aparshin** [comment]
Unfortunately, I don't think that this plugin is compatible with `L.TileLayer.PouchDBCached`.

The main problem is that `L.TileLayer.PouchDBCached` is developed to cache specifically `L.TileLayer`. But this plugin is based on `L.TileLayer.Canvas` (on `L.GridLayer` for v1.0) and uses Canvas elements instead of Image element in classical tiled layer.
